// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @title EnergyToken
 * @dev ERC-20 token representing renewable energy units (Wh)
 * 
 * One token = one Watt-hour of renewable energy generated by the wind turbine.
 * Tokens are minted hourly based on actual energy generation.
 * Tokens are burned when traded/consumed in the peer-to-peer energy marketplace.
 * 
 * Example: If turbine generates 5 MWh in one hour
 *   → Mint 5,000,000 ENERGY tokens (1 token = 1 Wh)
 *   → Available for trading in AuctionEngine
 *   → Burned upon settlement
 */
contract EnergyToken is ERC20, Ownable {
    
    // Events
    event TokensMinted(
        uint256 indexed hour,
        uint256 amount,
        uint256 energyGenerated,
        uint256 timestamp
    );
    
    event TokensBurned(
        uint256 indexed auctionId,
        uint256 amount,
        address indexed buyer,
        uint256 timestamp
    );
    
    event MinterAdded(address indexed minter);
    event MinterRemoved(address indexed minter);
    
    // State variables
    mapping(address => bool) public minters;  // Authorized minters (orchestrator, auction engine)
    mapping(uint256 => uint256) public hourlyMint;  // Track mints per hour
    uint256 public totalEnergyGenerated;  // Total Wh (not adjusted for decimal)
    
    // Constants
    uint8 public constant DECIMALS = 0;  // 1 token = 1 Wh (no decimals)
    
    constructor() ERC20("Renewable Energy", "ENERGY") Ownable(msg.sender) {
        // Initial setup - owner can mint
        minters[msg.sender] = true;
    }
    
    /**
     * @dev Add authorized minter (e.g., trading_orchestrator.py via Web3.py)
     */
    function addMinter(address _minter) external onlyOwner {
        require(_minter != address(0), "Invalid minter address");
        minters[_minter] = true;
        emit MinterAdded(_minter);
    }
    
    /**
     * @dev Remove authorized minter
     */
    function removeMinter(address _minter) external onlyOwner {
        minters[_minter] = false;
        emit MinterRemoved(_minter);
    }
    
    /**
     * @dev Mint new tokens based on hourly energy generation
     * Can only be called by authorized minters (orchestrator during hourly settlement)
     * 
     * @param _to Recipient address (usually AuctionEngine contract)
     * @param _hour Hour timestamp for tracking
     * @param _energyWh Energy generated in Wh (1 Wh = 1 token at decimal 0)
     */
    function mintHourlyGeneration(
        address _to,
        uint256 _hour,
        uint256 _energyWh
    ) external {
        require(minters[msg.sender], "Caller not authorized minter");
        require(_to != address(0), "Invalid recipient");
        require(_energyWh > 0, "Energy must be > 0");
        
        // Track hourly mint
        hourlyMint[_hour] = _energyWh;
        totalEnergyGenerated += _energyWh;
        
        // Mint tokens (1 token = 1 Wh)
        _mint(_to, _energyWh);
        
        emit TokensMinted(_hour, _energyWh, _energyWh, block.timestamp);
    }
    
    /**
     * @dev Burn tokens when energy is traded/consumed
     * Called by AuctionEngine during settlement
     * 
     * @param _auctionId Auction ID for tracking
     * @param _amount Amount to burn
     * @param _buyer Buyer address
     */
    function burnOnSettlement(
        uint256 _auctionId,
        uint256 _amount,
        address _buyer
    ) external {
        require(balanceOf(msg.sender) >= _amount, "Insufficient tokens to burn");
        require(_amount > 0, "Burn amount must be > 0");
        
        _burn(msg.sender, _amount);
        emit TokensBurned(_auctionId, _amount, _buyer, block.timestamp);
    }
    
    /**
     * @dev Get hourly generation for specific hour
     */
    function getHourlyGeneration(uint256 _hour) external view returns (uint256) {
        return hourlyMint[_hour];
    }
    
    /**
     * @dev Get total tokens currently in circulation
     */
    function getCirculatingSupply() external view returns (uint256) {
        return totalSupply();
    }
    
    /**
     * @dev Override decimals to return 0 (1 token = 1 Wh with no sub-units)
     */
    function decimals() public view override returns (uint8) {
        return DECIMALS;
    }
}
